### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by cocreature** [mattulbrich/llreve#12]
I talked today with Mattias and Vladimir about open sourcing llrêve/this repo and we considered the BSD3 license and the University of Illinois/NCSA Open Source License (used by LLVM). They seem to be identical (even the wording is identical in the three clauses) and since BSD3 is wider known (at least in my filterbubble) I would go with that.

@steohan and @Lein4d need to either agree to the BSD3 license or we make it clear that your code is not licensed under an open source license.

Once that is done I’ll add the license to the repo. @mattulbrich also needs to pull the trigger to make it public which can happen either before or after a license is added.

And in case anyone is wondering, we are linking against LLVM, Z3 and the tools for my bachelorthesis are linking against libgmp and include https://github.com/nlohmann/json. None of this contradicts a BSD3 license.

**Comment by mattulbrich** [comment]
llreve is now a public repository.
I have added a file header for every source file in the master branch
