### ISSUE TITLE
Marks without Loops

### ISSUE THREAD

**Issue by steohan** [mattulbrich/llreve#15]
Could Reve support marks without loops? At the moment the following example causes a malformed smt file:

```c
extern int __mark(int);

int foo(int result) {
	result += 1;
	__mark(1);
	result += 2;
	return result;
}
```

Current workaround is
```c
	while (__mark(1) & 0){};
```

**Comment by cocreature** [comment]
That’s already supported if you use `__splitmark` instead. I don’t think adding a heuristic that figures out when that is appropriate for normal marks is worth the trouble.

**Comment by steohan** [comment]
What is the difference between __splitmark and __mark, is that documented somewhere?

**Comment by cocreature** [comment]
__splitmark splits the cfg so that the mark is in a block on its own. It’s not yet documented anywhere.
