### ISSUE TITLE
SMT Error: Symbol -1 not declared

### ISSUE THREAD

**Issue by steohan** [mattulbrich/llreve#16]
The generation of the smt file is not working properly for the attached source, compared with it self:

`./reve test.c test.c > test.smt2; eld test.smt2`

Results in the error `Symbol -1 not declared`. Removing any line does not result in the error.

test.c:
```c
extern int foo();

int
main (int argc, char **argv)
{
  int a = 0;
  int nproc, ignore = 0;
      int c = foo();
      if (c == -1)
        return 1;
      if (c == 12)
        ignore = 42;

  nproc = ignore;
  return 0;
}
```

**Comment by cocreature** [comment]
Sorry about that, should be fixed in 12970b298675d698d9687b23d0f23323a4ff14ab.
